# Generated by Django 4.0.1 on 2022-07-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('user_photo', models.ImageField(upload_to='media/cursos')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
