# Generated by Django 4.0.6 on 2022-07-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staff_user_photo_staff_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='linkedin_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
