# Generated by Django 4.0.6 on 2022-08-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.CharField(default='portfolio-dev', max_length=100),
        ),
    ]
